# Generated by Django 4.1.7 on 2023-03-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название номинации')),
                ('nomination_letter', models.CharField(max_length=1, unique=True, verbose_name='Буква номинации')),
            ],
            options={
                'verbose_name': 'Конкурсная номинация',
                'verbose_name_plural': 'Конкурсные номинации',
            },
        ),
        migrations.AlterModelOptions(
            name='contestmaterial',
            options={'verbose_name': 'Конкурсный материал', 'verbose_name_plural': 'Конкурсные материалы'},
        ),
        migrations.AddField(
            model_name='contestmaterial',
            name='nomination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contestnomination'),
        ),
    ]
