# Generated by Django 4.1.7 on 2023-03-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_institution_alter_contestnomination_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Учреждение', 'verbose_name_plural': 'Учреждения'},
        ),
        migrations.AddField(
            model_name='institution',
            name='short_name',
            field=models.CharField(default='йцуйцуйцу', max_length=255, verbose_name='Краткое название учреждения'),
            preserve_default=False,
        ),
    ]
