# Generated by Django 4.1.7 on 2023-03-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contestmaterial_other_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestmaterial',
            name='other_authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_author', to='main.author'),
        ),
    ]
